from enum import StrEnum


class FailureType(StrEnum):
    INVALID_JSON = "INVALID_JSON"
    PARTIAL_JSON = "PARTIAL_JSON"
    WRAPPED_JSON = "WRAPPED_JSON"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    WRONG_TYPE = "WRONG_TYPE"
    INVALID_ENUM = "INVALID_ENUM"
    FORMAT_VIOLATION = "FORMAT_VIOLATION"
    HALLUCINATED_VALUE = "HALLUCINATED_VALUE"
    FIELD_CONFUSION = "FIELD_CONFUSION"
    SCOPE_CREEP = "SCOPE_CREEP"
    RATE_LIMITED = "RATE_LIMITED"
    LLM_UNAVAILABLE = "LLM_UNAVAILABLE"
    UNKNOWN = "UNKNOWN"


SYNTAX_FAILURES = {
    FailureType.INVALID_JSON,
    FailureType.PARTIAL_JSON,
    FailureType.WRAPPED_JSON,
}

SCHEMA_FAILURES = {
    FailureType.MISSING_REQUIRED_FIELD,
    FailureType.WRONG_TYPE,
    FailureType.INVALID_ENUM,
    FailureType.FORMAT_VIOLATION,
    FailureType.SCOPE_CREEP,
}

SEMANTIC_FAILURES = {
    FailureType.HALLUCINATED_VALUE,
    FailureType.FIELD_CONFUSION,
}

